### ISSUE TITLE
NullPointerException，点击时出现问题

### ISSUE THREAD

**Issue by easytome** [hongyangAndroid/FlowLayout#150]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhy.view.flowlayout.TagView.setChecked(boolean)' on a null object reference
       at com.zhy.view.flowlayout.TagFlowLayout.setChildUnChecked(SourceFile:163)
       at com.zhy.view.flowlayout.TagFlowLayout.doSelect(SourceFile:174)
       at com.zhy.view.flowlayout.TagFlowLayout.access$000(SourceFile:23)
       at com.zhy.view.flowlayout.TagFlowLayout$1.onClick(SourceFile:134)
       at android.view.View.performClick(View.java:5106)
       at android.view.View$PerformClick.run(View.java:20329)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by easytome** [comment]
@hongyangAndroid 
我看过另外一个空针异常，跟这个情况不一样，但是是在一个地方空针的
