### ISSUE TITLE
在 Umeng 捕捉到 TagFlowLayout.onRestoreInstanceState 发生的 Exception

### ISSUE THREAD

**Issue by Ctrl-Space** [hongyangAndroid/FlowLayout#17]
Caused by: java.lang.NullPointerException
	at com.mypackage.view.FlowLayout.TagFlowLayout.onRestoreInstanceState(Unknown Source)
	at android.view.View.dispatchRestoreInstanceState(View.java:12821)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2639)

在 Umeng 后台监控到在 MI3 / HW MT7/等机型中都出现这个NullPointerException，无法重现，不知道是不是这个库的问题。

**Comment by hongyangAndroid** [comment]
和[issue#22](https://github.com/hongyangAndroid/FlowLayout/issues/22)同样的情况，参考#22。
