### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhy.view.flowlayout.h.setChecked(boolean)' on a null object reference

### ISSUE THREAD

**Issue by guojilong** [hongyangAndroid/FlowLayout#22]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhy.view.flowlayout.h.setChecked(boolean)' on a null object reference
	at com.zhy.view.flowlayout.TagFlowLayout.onRestoreInstanceState(TagFlowLayout.java:269)
	at android.view.View.dispatchRestoreInstanceState(View.java:13621)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
	at android.view.View.restoreHierarchyState(View.java:13599)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:468)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2042)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5949)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by itxuye** [comment]
@hongyangAndroid  I have the same problem.

**Comment by hongyangAndroid** [comment]
多谢指出，原因是当View所在Activity因为内存不足被销毁后重建，该View在进行恢复时，调用`onRestoreInstanceState`方法，此方法依赖`setAdapter`，如果`setAdapter`在`onRestoreInstanceState`之后调用就会出现上述异常。

目前已经进行非null的判断，避免出现异常,可以查看最新的代码。

ps:建议查看setAdapter有没有可能调整到`onRestoreInstanceState`，例如`onCreate`中。
